Added test programs to usb_pio library. Updated raptor_make_deployment to include usb_pio library/test programs, and made filter_wheel/java programs always included in the deployment.

diff --git a/scripts/raptor_make_deployment b/scripts/raptor_make_deployment
--- a/scripts/raptor_make_deployment
+++ b/scripts/raptor_make_deployment
@@ -21,13 +21,9 @@ if ( "${machine_name}" == "-help") then
 endif
 switch ( ${machine_name} )
     case "raptor":
-	set install_java_software = 1
-	set install_filter_wheel_software = 1
 	setenv HOSTTYPE "x86_64-linux"
 	breaksw
     default:
-	set install_java_software = 1
-	set install_filter_wheel_software = 1
 	setenv HOSTTYPE "x86_64-linux"
 endsw
 set camera_name = "raptor"
@@ -86,13 +82,7 @@ endif
 #
 echo "Creating directory structure..."
 set dir_count = 0
-set dir_list = "${deployment_dir} ${deployment_dir}/${init_d_dir} ${deployment_icc_dir} ${deployment_bin_dir} ${deployment_dir}/icc/tmp ${deployment_dir}/icc/tmp/log_archive ${deployment_dir}/icc/log ${deployment_icc_dir}/config ${deployment_bin_dir}/scripts ${deployment_bin_dir}/raptor/scripts ${deployment_bin_dir}/raptor/c/${HOSTTYPE} ${deployment_bin_dir}/raptor/detector/test/${HOSTTYPE} ${deployment_bin_dir}/ics_util/c/${HOSTTYPE} ${deployment_bin_dir}/ccd/misc/${HOSTTYPE} ${deployment_bin_dir}/lib/${HOSTTYPE} ${deployment_bin_dir}/log_udp/test/${HOSTTYPE} ${deployment_bin_dir}/commandserver/test/${HOSTTYPE} ${deployment_bin_dir}/ngatastro/test/${HOSTTYPE} ${deployment_bin_dir}/javalib ${deployment_bin_dir}/autobooter/java "
-if( ${install_java_software} ) then
-    set dir_list = "${dir_list} ${deployment_bin_dir}/raptor/test ${deployment_bin_dir}/raptor/java/ ${deployment_bin_dir}/ics_gui/java ${deployment_bin_dir}/ics_gui/java/wav "
-endif
-if( ${install_filter_wheel_software} ) then
-    set dir_list = "${dir_list} ${deployment_bin_dir}/raptor/filter_wheel/test/${HOSTTYPE}"
-endif
+set dir_list = "${deployment_dir} ${deployment_dir}/${init_d_dir} ${deployment_icc_dir} ${deployment_bin_dir} ${deployment_dir}/icc/tmp ${deployment_dir}/icc/tmp/log_archive ${deployment_dir}/icc/log ${deployment_icc_dir}/config ${deployment_bin_dir}/scripts ${deployment_bin_dir}/raptor/scripts ${deployment_bin_dir}/raptor/test ${deployment_bin_dir}/raptor/java/ ${deployment_bin_dir}/ics_gui/java ${deployment_bin_dir}/ics_gui/java/wav ${deployment_bin_dir}/raptor/c/${HOSTTYPE} ${deployment_bin_dir}/raptor/detector/test/${HOSTTYPE} ${deployment_bin_dir}/raptor/filter_wheel/test/${HOSTTYPE} ${deployment_bin_dir}/raptor/usb_pio/test/${HOSTTYPE} ${deployment_bin_dir}/ics_util/c/${HOSTTYPE} ${deployment_bin_dir}/ccd/misc/${HOSTTYPE} ${deployment_bin_dir}/lib/${HOSTTYPE} ${deployment_bin_dir}/log_udp/test/${HOSTTYPE} ${deployment_bin_dir}/commandserver/test/${HOSTTYPE} ${deployment_bin_dir}/ngatastro/test/${HOSTTYPE} ${deployment_bin_dir}/javalib ${deployment_bin_dir}/autobooter/java "
 foreach dir ( ${dir_list} )
 	mkdir -p ${dir}
 	if ($status != 0) then
@@ -106,11 +96,8 @@ echo "${dir_count} directories created."
 # Copy jars
 #
 echo "Copying jars..."
-set jar_list = "ngat_message_base.jar ngat_message_inst_dp.jar ngat_message_iss_inst.jar ngat_net.jar ngat_phase2.jar ngat_util.jar ngat_util_logging.jar"
+set jar_list = "ngat_message_base.jar ngat_message_inst_dp.jar ngat_message_iss_inst.jar ngat_net.jar ngat_phase2.jar ngat_util.jar ngat_util_logging.jar ngat_fits.jar ngat_swing.jar ngat_sound.jar"
 # ngat_raptor.jar 
-if( ${install_java_software} ) then
-    set jar_list = "${jar_list} ngat_fits.jar ngat_swing.jar ngat_sound.jar"
-endif
 set jar_count = 0
 foreach jar ( ${jar_list} )
 	echo "jar : ${jar}"
@@ -145,10 +132,7 @@ echo "${jar_count} jars copied."
 # Java classes
 #
 echo "Copying Java class directories..."
-set java_class_dir_list = "autobooter/java"
-if( ${install_java_software} ) then
-    set java_class_dir_list = "${java_class_dir_list} ics_gui/java"
-endif
+set java_class_dir_list = "autobooter/java ics_gui/java"
 set java_class_dir_count = 0
 set java_class_file_count = 0
 foreach java_class_dir ( ${java_class_dir_list} )
@@ -183,7 +167,7 @@ echo "${java_class_dir_count} Java class directories copied with ${java_class_fi
 # C libraries
 #
 echo "Copying C libraries..."
-set clib_list = "libcfitsio.so libngatastro.so libngatutil.so libestar_config.so liblog_udp.so libcommandserver.so libraptor_filter_wheel.so"
+set clib_list = "libcfitsio.so libngatastro.so libngatutil.so libestar_config.so liblog_udp.so libcommandserver.so libraptor_filter_wheel.so libraptor_usb_pio.so"
 set clib_count = 0
 foreach clib ( ${clib_list} )
 	echo "C Library : ${clib}"
@@ -221,10 +205,7 @@ echo "${clib_count} C libraries copied."
 # C programs
 #
 echo "Copying C program directories..."
-set dir_list = "ics_util/c/${HOSTTYPE} ccd/misc/${HOSTTYPE} log_udp/test/${HOSTTYPE} ngatastro/test/${HOSTTYPE} commandserver/test/${HOSTTYPE} raptor/c/${HOSTTYPE} raptor/detector/test/${HOSTTYPE} "
-if( ${install_filter_wheel_software} ) then
-    set dir_list = "${dir_list} raptor/filter_wheel/test/${HOSTTYPE}"
-endif
+set dir_list = "ics_util/c/${HOSTTYPE} ccd/misc/${HOSTTYPE} log_udp/test/${HOSTTYPE} ngatastro/test/${HOSTTYPE} commandserver/test/${HOSTTYPE} raptor/c/${HOSTTYPE} raptor/detector/test/${HOSTTYPE} raptor/filter_wheel/test/${HOSTTYPE} raptor/usb_pio/test/${HOSTTYPE}"
 set dir_count = 0
 set file_count = 0
 # clean out deployment_tmp_dir
@@ -275,10 +256,7 @@ echo "${dir_count} C test program directories copied, containg ${file_count} C t
 # Scripts
 #
 echo "Copying scripts..."
-set file_list = "bin/scripts/configure_tai_data.csh bin/scripts/delete_log_files.csh bin/scripts/killhup.csh bin/scripts/fuser_check bin/raptor/scripts/raptor_engineering_mode"
-if( ${install_java_software} ) then
-    set file_list = "${file_list} bin/ics_gui/java/icsgui"
-endif
+set file_list = "bin/scripts/configure_tai_data.csh bin/scripts/delete_log_files.csh bin/scripts/killhup.csh bin/scripts/fuser_check bin/raptor/scripts/raptor_engineering_mode bin/ics_gui/java/icsgui"
 set file_count = 0
 cd ${dev_dir}
 foreach file ( ${file_list} )
@@ -299,9 +277,7 @@ echo "${file_count} scripts copied."
 echo "Copying machine configuration files..."
 # raptor/c/${HOSTTYPE}/${machine_name}.raptor.c.properties
 set file_list = "autobooter/java/${machine_name}.autobooter.properties "
-#if( ${install_java_software} ) then
-#    set file_list = "${file_list} raptor/java/${machine_name}.fits.properties raptor/java/${machine_name}.raptor.net.properties raptor/java/${machine_name}.raptor.properties ics_gui/java/${machine_name}.ics_gui.properties ics_gui/java/${machine_name}.ics_gui_config.properties ics_gui/java/${machine_name}.ics_gui.fits.properties"
-#endif
+# raptor/java/${machine_name}.fits.properties raptor/java/${machine_name}.raptor.net.properties raptor/java/${machine_name}.raptor.properties ics_gui/java/${machine_name}.ics_gui.properties ics_gui/java/${machine_name}.ics_gui_config.properties ics_gui/java/${machine_name}.ics_gui.fits.properties"
 set file_count = 0
 cd ${dev_dir}
 foreach file ( ${file_list} )
@@ -346,22 +322,20 @@ endif
 #
 # gif files
 #
-if( ${install_java_software} ) then
-    echo "Copying gif/wav files..."
-    set file_list = "ics_gui/java/lt_icon.gif ics_gui/java/lt.gif ics_gui/java/wav/command_completed.wav ics_gui/java/wav/command_failed.wav ics_gui/java/wav/filename.wav ics_gui/java/wav/iss_message.wav ics_gui/java/wav/welcome.wav"
-    set file_count = 0
-    cd ${dev_dir}
-    foreach file ( ${file_list} )
-	cp ${dev_bin_dir}/${file} ${deployment_bin_dir}/${file}
-	set cp_status = $status
-	if( ${cp_status} != 0 ) then
-	    echo "Copy failed: ${dev_bin_dir}/${file} to ${deployment_bin_dir}/${file}"
-	    exit 6
-	endif
-	@ file_count ++
-    end
-    echo "${file_count} gif/wav files copied."
-endif
+echo "Copying gif/wav files..."
+set file_list = "ics_gui/java/lt_icon.gif ics_gui/java/lt.gif ics_gui/java/wav/command_completed.wav ics_gui/java/wav/command_failed.wav ics_gui/java/wav/filename.wav ics_gui/java/wav/iss_message.wav ics_gui/java/wav/welcome.wav"
+set file_count = 0
+cd ${dev_dir}
+foreach file ( ${file_list} )
+    cp ${dev_bin_dir}/${file} ${deployment_bin_dir}/${file}
+    set cp_status = $status
+    if( ${cp_status} != 0 ) then
+	echo "Copy failed: ${dev_bin_dir}/${file} to ${deployment_bin_dir}/${file}"
+	exit 6
+    endif
+    @ file_count ++
+end
+echo "${file_count} gif/wav files copied."
 #
 # Tidy deployment temp
 #
